package com.mindai.model;

import com.mindai.model.base.BaseDataSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataSource extends BaseDataSource<DataSource> {
	public static final DataSource dao = new DataSource().dao();
}
