package com.mindai.model;

import com.mindai.model.base.BaseExecuteList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExecuteList extends BaseExecuteList<ExecuteList> {
	public static final ExecuteList dao = new ExecuteList().dao();
}
