package com.mindai.model;

import com.mindai.model.base.BaseJobList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JobList extends BaseJobList<JobList> {
	public static final JobList dao = new JobList().dao();
}
