package com.mindai.model;

import com.mindai.model.base.BaseScheduleInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ScheduleInfo extends BaseScheduleInfo<ScheduleInfo> {
	public static final ScheduleInfo dao = new ScheduleInfo().dao();
}
