package com.mindai.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExecuteList<M extends BaseExecuteList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setRefScheduleId(java.lang.Integer refScheduleId) {
		set("refScheduleId", refScheduleId);
	}

	public java.lang.Integer getRefScheduleId() {
		return get("refScheduleId");
	}

	public void setExecuteLog(java.lang.String executeLog) {
		set("executeLog", executeLog);
	}

	public java.lang.String getExecuteLog() {
		return get("executeLog");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setStartTime(java.lang.String startTime) {
		set("startTime", startTime);
	}

	public java.lang.String getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.lang.String endTime) {
		set("endTime", endTime);
	}

	public java.lang.String getEndTime() {
		return get("endTime");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

}
