package com.mindai.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScheduleInfo<M extends BaseScheduleInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setScheduleName(java.lang.String scheduleName) {
		set("scheduleName", scheduleName);
	}

	public java.lang.String getScheduleName() {
		return get("scheduleName");
	}

	public void setRefJobId(java.lang.Integer refJobId) {
		set("refJobId", refJobId);
	}

	public java.lang.Integer getRefJobId() {
		return get("refJobId");
	}

	public void setScheduleType(java.lang.Integer scheduleType) {
		set("scheduleType", scheduleType);
	}

	public java.lang.Integer getScheduleType() {
		return get("scheduleType");
	}

	public void setSchedule(java.lang.String schedule) {
		set("schedule", schedule);
	}

	public java.lang.String getSchedule() {
		return get("schedule");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

}
