package com.mindai.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJobList<M extends BaseJobList<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setJobName(java.lang.String jobName) {
		set("jobName", jobName);
	}

	public java.lang.String getJobName() {
		return get("jobName");
	}

	public void setRefSrcDbSourceId(java.lang.Integer refSrcDbSourceId) {
		set("refSrcDbSourceId", refSrcDbSourceId);
	}

	public java.lang.Integer getRefSrcDbSourceId() {
		return get("refSrcDbSourceId");
	}

	public void setSrcBase(java.lang.String srcBase) {
		set("srcBase", srcBase);
	}

	public java.lang.String getSrcBase() {
		return get("srcBase");
	}

	public void setSrcTable(java.lang.String srcTable) {
		set("srcTable", srcTable);
	}

	public java.lang.String getSrcTable() {
		return get("srcTable");
	}

	public void setRefDstDbSourceId(java.lang.Integer refDstDbSourceId) {
		set("refDstDbSourceId", refDstDbSourceId);
	}

	public java.lang.Integer getRefDstDbSourceId() {
		return get("refDstDbSourceId");
	}

	public void setDstBase(java.lang.String dstBase) {
		set("dstBase", dstBase);
	}

	public java.lang.String getDstBase() {
		return get("dstBase");
	}

	public void setDstTable(java.lang.String dstTable) {
		set("dstTable", dstTable);
	}

	public java.lang.String getDstTable() {
		return get("dstTable");
	}

	public void setIncrementColumn(java.lang.String incrementColumn) {
		set("incrementColumn", incrementColumn);
	}

	public java.lang.String getIncrementColumn() {
		return get("incrementColumn");
	}

	public void setIncrementColumnVal(java.lang.String incrementColumnVal) {
		set("incrementColumnVal", incrementColumnVal);
	}

	public java.lang.String getIncrementColumnVal() {
		return get("incrementColumnVal");
	}

	public void setJobRule(java.lang.String jobRule) {
		set("jobRule", jobRule);
	}

	public java.lang.String getJobRule() {
		return get("jobRule");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

}
